CREATE TABLE `tb_customer` (
	`userno` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`userid` VARCHAR(50) NOT NULL,
	`email` VARCHAR(100) NOT NULL,
	`passwd` VARCHAR(30) NULL DEFAULT NULL,
	`name` VARCHAR(30) NULL DEFAULT NULL,
	`mobile` VARCHAR(20) NULL DEFAULT NULL,
	`retireYN` TINYINT(1) NULL DEFAULT '1',
	`InsertUID` VARCHAR(40) NULL DEFAULT NULL,
	`InsertDT` DATETIME NULL DEFAULT NULL,
	`UpdateUID` VARCHAR(40) NULL DEFAULT NULL,
	`UpdateDT` DATETIME NULL DEFAULT NULL,
	`adress` VARCHAR(50) NULL DEFAULT NULL,
	`coin` INT(11) NULL DEFAULT NULL,
	`mileage` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`userno`),
	UNIQUE INDEX `userid` (`userid`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
